name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce it
      description: Provide a clear set of steps to reproduce the bug.
      placeholder: |
        1. Run `hassflux migrate`
        2. See error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please provide any relevant logs or error messages.
      render: shell
  - type: input
    id: version
    attributes:
      label: Hassflux Version
      description: What version of Hassflux are you using?
      placeholder: e.g. v0.1.0
    validations:
      required: true
